export const actionsTypes = {
    // file upload state
    UPDATE_PERCENT: "UPDATE_PERCENT",
    UPDATE_REQUEST_FILE_COUNT: "UPDATE_REQUEST_FILE_COUNT",
    UPDATE_SUCCESS_FILE_COUNT: "UPDATE_SUCCESS_FILE_COUNT",

    // server action key
    SERVER_ACTION: "SERVER_ACTION",
};